import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'

import Footer from '@/components/Footer/Footer'

const montserrat = Montserrat({
   subsets: ['latin'],
})

export const metadata: Metadata = {
   title: 'World of Tanks Index',
   description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html className={montserrat.className} lang='en'>
         <body>
            {children}
            <Footer />
         </body>
      </html>
   )
}
