import type { Metadata } from 'next'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'

import { Montserrat } from 'next/font/google'
import './globals.css'

import ThemeProvider from '@/ProvidersThemeProvider'

import Footer from '@/components/Footer/Footer'
import Navbar from '@/componentsNavbar/Navbar'

const montserrat = Montserrat({
   subsets: ['latin'],
})

export const metadata: Metadata = {
   title: 'World of Tanks Index',
   description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html className={montserrat.className} lang='en'>
         <AppRouterCacheProvider options={{ enableCssLayer: true }}>
            <ThemeProvider>
               <body>
                  <Navbar />
                  <main className='max-w-screen-2xl mx-auto px-5'>{children}</main>
                  <Footer />
               </body>
            </ThemeProvider>
         </AppRouterCacheProvider>
      </html>
   )
}
